[versions]
activity = "1.11.0"
agp = "8.9.1"
espressoCore = "3.7.0"
kotlin = "2.0.0"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.3.0"
kotlinxCoroutinesAndroid = "1.10.2"
orgJacocoCore = "0.8.13"
room-version = "2.7.2"
gson = "2.11.0"
compressor = "3.0.1"
networkresponseadapter = "5.0.0"
retrofit-version = "2.11.0"
roomTesting = "2.7.2"
textRecognition = "16.0.1"
workRuntimeKtx = "2.8.1"
playServicesMlkitDocumentScanner = "16.0.0-beta1"
network = "2.0.3"
coreKtxVersion = "1.7.0"

[libraries]
androidx-activity = { module = "androidx.activity:activity", version.ref = "activity" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "roomTesting" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
org-jacoco-core = { module = "org.jacoco:org.jacoco.core", version.ref = "orgJacocoCore" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room-version" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room-version" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room-version" }
google-gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
text-recognition = { module = "com.google.mlkit:text-recognition", version.ref = "textRecognition" }
zelory-compressor = { module = "id.zelory:compressor", version.ref = "compressor" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit-version" }
retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit-version" }
haroldadmin-networkresponseadapter = { module = "com.github.haroldadmin:NetworkResponseAdapter", version.ref = "networkresponseadapter" }
play-services-mlkit-document-scanner = { group = "com.google.android.gms", name = "play-services-mlkit-document-scanner", version.ref = "playServicesMlkitDocumentScanner" }
eka-network = { group = "com.github.eka-care", name = "eka-network-android", version.ref = "network" }
core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "coreKtxVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }